### ISSUE TITLE
Super User Access

### ISSUE THREAD

**Issue by JMSolo** [offiria/offiria#3] opened 2013-08-14 12:35 UTC
Users do not have the ability to properly access the backend.

SOLUTION::

Enter your database via PHPMyAdmin (Or the given resource made available to you for editeing your DB) and change the following table:

_user_usergroup_map 
... edit column with default user id ("42") to have the usergroup.id ("8"). 
(note - the default group id is 7, ie; Administrator)

This will unlock Super User throughout.

![adke25p7](https://f.cloud.github.com/assets/5215074/961683/fd301a96-04dd-11e3-9ef7-fb40753d430f.png)

ADDITIONAL NOTES:: 

We have applied the above method and have installed a proper Akeeba Pro subscript as well as AdminTools.  SuperUser becomes selectable.

No issues have risen as a result of applying this solution.

**Comment by offiria** [comment] 2013-09-06 01:08
Thanks, we could add this in the wiki, but I won't fix this in the code. By design, we don't really want people to have the need to access the backend. But i suppose for those who know what they are doing, they would need this.

**Closed as completed by offiria** 2013-09-06 01:08 UTC
Labels: wontfix

**Comment by hsali** [comment] 2015-02-06 11:09
This method will not work. Please, also map the user id and group-id in table _user_group_map in v 2.x of offiria.
